### ISSUE TITLE
Getting an error in backend.js while deploying it on heroku

### ISSUE THREAD

**Issue by spydee007** [jpillora/node-torrent-cloud#13]
## Below is the error observed in the logs 

2016-10-01T09:38:24.791201+00:00 app[web.1]:     at Module._compile (module.js:387:25)

2016-10-01T09:38:24.791208+00:00 app[web.1]:     at Object.Module._extensions..js (module.js:422:10)

2016-10-01T09:38:24.791208+00:00 app[web.1]:     at Module.load (module.js:357:32)

2016-10-01T09:38:24.791209+00:00 app[web.1]:     at Function.Module._load (module.js:314:12)

2016-10-01T09:38:24.791209+00:00 app[web.1]:     at Module.require (module.js:367:17)

2016-10-01T09:38:24.791210+00:00 app[web.1]:     at require (internal/module.js:20:19)

2016-10-01T09:38:24.791210+00:00 app[web.1]:     at /app/lib/backend.js:26:16

2016-10-01T09:38:24.791210+00:00 app[web.1]:     at Array.forEach (native)

2016-10-01T09:38:24.791214+00:00 app[web.1]:     at Object.<anonymous> (/app/lib/backend.js:21:10)

2016-10-01T09:38:32.818604+00:00 heroku[web.1]: State changed from crashed to down
[1.txt](https://github.com/jpillora/node-torrent-cloud/files/504265/1.txt)

**Comment by jpillora** [comment]
@rakshans1 can you check if this is related to the previous change?

**Comment by spydee007** [comment]
@jpillora i have attached the logs in 1.txt file

**Comment by rakshans1** [comment]
@spydee007 did you add env variable....also heroku is suspending this app automatically if you deploy via heroku button

**Comment by spydee007** [comment]
@rakshans1 yes i have added env var , also provided search var json file. i guess heroku is suspending the app coz now if i check the app setting it show that my app is suspended.
so as a workaround should i try cloning to my repo and then connecting it via GitHub or is there something else?

**Comment by spydee007** [comment]
Heroku will suspend the app with bit torrent source codes/torrent programs.
