### ISSUE TITLE
get this error while trying to run on window 7

### ISSUE THREAD

**Issue by buziyborni** [jpillora/node-torrent-cloud#7]
please i need help on how to run this app on window i have install node and npm but i get this error please help me on how to fix it.
Your environment has been set up for using Node.js 4.2.1 (ia32) and npm.

C:\Users\Buziyborni>cd C:\Users\Buziyborni\Desktop\ability\torrentcloud

C:\Users\Buziyborni\Desktop\ability\node-torrent-cloud>node server.js
module.js:453
    throw err;
    ^

SyntaxError: C:\Users\Buziyborni\Desktop\ability\node-torrent-cloud\config.json: Unexp
ected token b
    at Object.parse (native)
    at Object.Module._extensions..json (module.js:450:27)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (C:\Users\Buziyborni\Desktop\ability\node-torrent-cloud\serv
er.js:2:14)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)

C:\Users\Buziyborni\Desktop\ability\node-torrent-cloud>

**Comment by bharadwajpro** [comment]
Add Mega or AWS credentials in `config.json` or in the Environment Variables in Windows
